{{- if .Values.watcher.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
  namespace: {{ .Values.namespaces.kubeWatcher }}
  labels:
    app: watcher
    {{- include "kube-watcher.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl .Values.watcher.configYaml . | indent 4 }}
{{- end }}
