{{- $namespace := .Values.namespaces.anomstack -}}
{{- if and .Values.signoz.enabled (not (lookup "v1" "Namespace" "" $namespace)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    app: signoz
{{- end }}
