// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alerts/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/[id].get').default>>>>
    }
    '/api/alerts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/index.get').default>>>>
    }
    '/api/alerts/ingest': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/ingest.post').default>>>>
    }
    '/api/alerts/stream': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/stream.get').default>>>>
    }
    '/api/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}