ARG BUILD_IMAGE=golang:1.25.1-alpine3.21
ARG RUNTIME_IMAGE=alpine:3.21
ARG DEBUG_RUNTIME_IMAGE=alpine:3.21

ARG SERVICE_ROOT
ARG SERVICE_CMD=./cmd/server
ARG VERSION=dev
ARG GIT_COMMIT=unknown
ARG BUILD_DATE=unknown


FROM --platform=$BUILDPLATFORM ${BUILD_IMAGE} AS builder

ARG SERVICE_ROOT
ARG SERVICE_CMD
ARG VERSION
ARG GIT_COMMIT
ARG BUILD_DATE

ENV CGO_ENABLED=0
WORKDIR /src

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .
WORKDIR /src/${SERVICE_ROOT}

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go build -ldflags="-s -w -X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildDate=${BUILD_DATE}" \
    -o /out/app ${SERVICE_CMD}

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go build -gcflags="all=-N -l" \
    -o /out/app-debug ${SERVICE_CMD}

# Debug image
FROM ${DEBUG_RUNTIME_IMAGE} AS runner-debug
COPY --from=builder /out/app-debug /app/main
USER root
RUN mkdir -p /home/nonroot /app && chown -R 65532:65532 /home/nonroot /app
ENV HOME=/home/nonroot
USER 65532:65532
ENTRYPOINT ["/app/main"]

# Final slim image
FROM ${RUNTIME_IMAGE} AS final
COPY --from=builder /out/app /app/main
USER root
RUN mkdir -p /home/nonroot /app && chown -R 65532:65532 /home/nonroot /app
ENV HOME=/home/nonroot
USER 65532:65532
ENTRYPOINT ["/app/main"]
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD ["/app/main", "--health"]
