apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kw-anomaly
resources:
  - namespace.yaml
  - configmap-env.yaml
  - configmap-metrics.yaml
  - pvc.yaml
  - anomstack-services.yaml
  - anomstack-nginx-config.yaml
  - deploy-webserver.yaml
  - deploy-daemon.yaml
  - deploy-dashboard.yaml
  - mock-feeder.yaml
