apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"kw-anomaly"}}
  creationTimestamp: "2026-03-31T19:33:02Z"
  labels:
    kubernetes.io/metadata.name: kw-anomaly
  name: kw-anomaly
  resourceVersion: "100412"
  uid: 3033262e-8683-4f2d-bdac-42065d152f16
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
