# This formula is auto-generated by GoReleaser on release.
# To use it manually, copy this file to your homebrew-tap repo:
#   drewjocham/homebrew-tap/Formula/kube-watcher.rb
#
# Update the `url`, `sha256`, and `version` fields for each release.

class KubeWatcher < Formula
  desc "Kubernetes monitoring MCP server and CLI — exposes cluster insights to AI assistants and REST APIs"
  homepage "https://github.com/drewjocham/kubernetes-mcp"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/drewjocham/kubernetes-mcp/releases/download/v#{version}/kube-watcher_#{version}_darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_AFTER_RELEASE"
    end

    on_intel do
      url "https://github.com/drewjocham/kubernetes-mcp/releases/download/v#{version}/kube-watcher_#{version}_darwin_amd64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_AFTER_RELEASE"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drewjocham/kubernetes-mcp/releases/download/v#{version}/kube-watcher_#{version}_linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_AFTER_RELEASE"
    end

    on_intel do
      url "https://github.com/drewjocham/kubernetes-mcp/releases/download/v#{version}/kube-watcher_#{version}_linux_amd64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_AFTER_RELEASE"
    end
  end

  def install
    bin.install "kube-watcher"
    bin.install "kw-cli"
    # Create kw symlink for convenience
    bin.install_symlink "kw-cli" => "kw"
  end

  test do
    system "#{bin}/kube-watcher", "--version"
    system "#{bin}/kw", "version"
  end
end
