import type { AlertIngestPayload, AlertKind, AlertRecord, RCAReport } from '~/types/alerts'
import { getWorkflowConfig, pushThinkingStep, setFailed, setReport, setThinking, updateAlert } from '~/server/utils/alert-store'

function wait(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function nowISO() {
  return new Date().toISOString()
}

async function fetchDiagnostics(alert: AlertRecord): Promise<AlertIngestPayload['diagnostics']> {
  if (alert.diagnostics) return alert.diagnostics

  const config = getWorkflowConfig()
  if (!config.mcpEndpoint) {
    return {
      lastLogLines: [
        `${alert.pod}: simulated ${alert.kind} probe`,
        `container=${alert.container ?? 'unknown'} state=waiting reason=${alert.kind}`
      ],
      describeOutput: `Pod ${alert.pod} in namespace ${alert.namespace} requires further describe output`,
      clusterEvents: ['No external MCP endpoint configured. Returned synthetic diagnostics.']
    }
  }

  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (config.mcpApiKey) {
    headers[config.mcpApiKeyHeader] = config.mcpApiKeyHeader.toLowerCase() === 'authorization'
      ? `Bearer ${config.mcpApiKey}`
      : config.mcpApiKey
  }

  const payload = {
    namespace: alert.namespace,
    pod: alert.pod,
    kind: alert.kind,
    lines: 50
  }

  const response = await fetch(config.mcpEndpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify(payload)
  })
  if (!response.ok) {
    throw new Error(`MCP diagnostics failed with ${response.status}`)
  }

  return await response.json() as AlertIngestPayload['diagnostics']
}

function fallbackReport(kind: AlertKind, diagnostics?: AlertIngestPayload['diagnostics']): RCAReport {
  const base: Record<AlertKind, Omit<RCAReport, 'generatedAt'>> = {
    CrashLoopBackOff: {
      summary: 'Pod repeatedly crashes shortly after startup.',
      rootCause: 'Likely bad runtime configuration, missing dependency, or failed startup probe.',
      recommendedActions: [
        'Review the latest 50 log lines for startup panic or connection failure.',
        'Validate referenced Secrets/ConfigMaps and env var names.',
        'If probe failures are expected during warmup, tune startupProbe/readinessProbe thresholds.'
      ],
      confidence: 'medium'
    },
    OOMKilled: {
      summary: 'Container is terminated due to memory pressure.',
      rootCause: 'Memory limit is lower than workload peak usage.',
      recommendedActions: [
        'Increase memory requests/limits for the affected container.',
        'Inspect heap growth and batch size; cap unbounded in-memory caching.',
        'Enable memory profiling and set alerting before hard OOM.'
      ],
      confidence: 'high'
    },
    ImagePullBackOff: {
      summary: 'Pod cannot pull container image.',
      rootCause: 'Image tag, registry auth, or imagePullSecret reference is invalid.',
      recommendedActions: [
        'Verify image path/tag exists in registry.',
        'Validate imagePullSecrets and namespace-scoped credentials.',
        'Check registry/network policy reachability from cluster nodes.'
      ],
      confidence: 'high'
    },
    Unknown: {
      summary: 'Pod entered an unhealthy state that needs investigation.',
      rootCause: 'Insufficient context to classify exact failure.',
      recommendedActions: [
        'Collect logs, describe output, and cluster events around firstSeenAt.',
        'Correlate with deployment and config changes.',
        'Escalate to platform team if repeated across namespaces.'
      ],
      confidence: 'low'
    }
  }

  const report = base[kind]
  const signal = diagnostics?.clusterEvents?.[0]
  return {
    generatedAt: nowISO(),
    ...report,
    summary: signal ? `${report.summary} Signal: ${signal}` : report.summary
  }
}

async function generateReport(alert: AlertRecord, diagnostics?: AlertIngestPayload['diagnostics']): Promise<RCAReport> {
  const config = getWorkflowConfig()
  if (!config.agentEndpoint) {
    return fallbackReport(alert.kind, diagnostics)
  }

  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (config.agentApiKey) {
    headers[config.agentApiKeyHeader] = config.agentApiKeyHeader.toLowerCase() === 'authorization'
      ? `Bearer ${config.agentApiKey}`
      : config.agentApiKey
  }

  const payload = {
    alert,
    diagnostics,
    task: 'Generate Kubernetes RCA with remediation guidance'
  }

  const response = await fetch(config.agentEndpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify(payload)
  })
  if (!response.ok) {
    throw new Error(`Agent report generation failed with ${response.status}`)
  }

  const body = await response.json() as Partial<RCAReport>
  return {
    generatedAt: body.generatedAt ?? nowISO(),
    summary: body.summary ?? 'RCA generated by external agent',
    rootCause: body.rootCause ?? 'See full agent output',
    recommendedActions: body.recommendedActions ?? [],
    confidence: body.confidence ?? 'medium'
  }
}

export async function runWorkflow(alertID: string) {
  const alert = updateAlert(alertID, (current) => current)
  if (!alert) return

  try {
    setThinking(alertID)
    pushThinkingStep(alertID, {
      at: nowISO(),
      title: 'Observer → API',
      details: `Alert ${alert.kind} received from ${alert.source}`
    })

    await wait(350)
    pushThinkingStep(alertID, {
      at: nowISO(),
      title: 'Thinker (MCP)',
      details: 'Collecting logs, describe output, and cluster events.'
    })

    const diagnostics = await fetchDiagnostics(alert)
    updateAlert(alertID, (current) => ({ ...current, diagnostics }))

    await wait(350)
    pushThinkingStep(alertID, {
      at: nowISO(),
      title: 'Actor (Agent)',
      details: 'Generating root-cause analysis and remediation steps.'
    })

    const report = await generateReport(alert, diagnostics)
    setReport(alertID, report)
  } catch (error) {
    setFailed(alertID, error instanceof Error ? error.message : 'unknown workflow error')
  }
}
