// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1, arg2) {
  return window['go']['main']['App']['AskAI'](arg1, arg2);
}

export function ExecuteTool(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTool'](arg1, arg2);
}

export function GetAIWorkspace() {
  return window['go']['main']['App']['GetAIWorkspace']();
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetEndpoint() {
  return window['go']['main']['App']['GetEndpoint']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetRecommendations() {
  return window['go']['main']['App']['GetRecommendations']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunSynapseSweep() {
  return window['go']['main']['App']['RunSynapseSweep']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
