// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {http} from '../models';

export function AddAlertComment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AskAI(arg1:string,arg2:string):Promise<string>;

export function DeleteWidget(arg1:string):Promise<void>;

export function DeployAnomstack(arg1:string):Promise<string>;

export function DescribePod(arg1:string,arg2:string):Promise<string>;

export function ExecPodCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExecuteTool(arg1:string,arg2:Record<string, any>):Promise<data.ToolResult>;

export function GetAIWorkspace():Promise<data.AIWorkspace>;

export function GetAlerts():Promise<Array<data.AlertRecord>>;

export function GetAnomstackAnomalies():Promise<Array<data.AlertRecord>>;

export function GetCurrentContext():Promise<string>;

export function GetEndpoint():Promise<string>;

export function GetHistory():Promise<Array<data.Incident>>;

export function GetNamespaces():Promise<Array<string>>;

export function GetPodAIHelp(arg1:string,arg2:string):Promise<string>;

export function GetPodLogs(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPodYAML(arg1:string,arg2:string):Promise<string>;

export function GetPods(arg1:string):Promise<Array<data.PodInfo>>;

export function GetRecommendations():Promise<Array<data.Recommendation>>;

export function GetStatus():Promise<data.StatusResponse>;

export function GetWatcherConfig():Promise<Record<string, any>>;

export function GetWatcherResources():Promise<Array<string>>;

export function GetWatcherRules():Promise<Array<any>>;

export function GetWatcherStatus():Promise<Record<string, any>>;

export function GetWidgets():Promise<Array<data.Widget>>;

export function Greet(arg1:string):Promise<string>;

export function RunCommand(arg1:string):Promise<string>;

export function RunSynapseSweep():Promise<string>;

export function SaveWidget(arg1:data.Widget):Promise<void>;

export function StreamWatcherLogs():Promise<http.Response>;

export function UpdateAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateAlertState(arg1:string,arg2:string):Promise<void>;
