// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlertComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAlertComment'](arg1, arg2, arg3);
}

export function AskAI(arg1, arg2) {
  return window['go']['main']['App']['AskAI'](arg1, arg2);
}

export function DeployAnomstack(arg1) {
  return window['go']['main']['App']['DeployAnomstack'](arg1);
}

export function DescribePod(arg1, arg2) {
  return window['go']['main']['App']['DescribePod'](arg1, arg2);
}

export function ExecPodCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecPodCommand'](arg1, arg2, arg3, arg4);
}

export function ExecuteTool(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTool'](arg1, arg2);
}

export function GetAIWorkspace() {
  return window['go']['main']['App']['GetAIWorkspace']();
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetAnomstackAnomalies() {
  return window['go']['main']['App']['GetAnomstackAnomalies']();
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetEndpoint() {
  return window['go']['main']['App']['GetEndpoint']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetNamespaces() {
  return window['go']['main']['App']['GetNamespaces']();
}

export function GetPodAIHelp(arg1, arg2) {
  return window['go']['main']['App']['GetPodAIHelp'](arg1, arg2);
}

export function GetPodLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPodLogs'](arg1, arg2, arg3);
}

export function GetPodYAML(arg1, arg2) {
  return window['go']['main']['App']['GetPodYAML'](arg1, arg2);
}

export function GetPods(arg1) {
  return window['go']['main']['App']['GetPods'](arg1);
}

export function GetRecommendations() {
  return window['go']['main']['App']['GetRecommendations']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunSynapseSweep() {
  return window['go']['main']['App']['RunSynapseSweep']();
}

export function UpdateAIConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAIConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateAlertState(arg1, arg2) {
  return window['go']['main']['App']['UpdateAlertState'](arg1, arg2);
}
