// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function AskAI(arg1:string,arg2:string):Promise<string>;

export function ExecuteTool(arg1:string,arg2:Record<string, any>):Promise<data.ToolResult>;

export function GetAIWorkspace():Promise<data.AIWorkspace>;

export function GetAlerts():Promise<Array<data.AlertRecord>>;

export function GetEndpoint():Promise<string>;

export function GetHistory():Promise<Array<data.Incident>>;

export function GetLogs():Promise<Array<data.LogLine>>;

export function GetRecommendations():Promise<Array<data.Recommendation>>;

export function GetServiceStatus():Promise<Array<data.ServiceStatus>>;

export function GetStatus():Promise<data.StatusResponse>;

export function Greet(arg1:string):Promise<string>;

export function RunCommand(arg1:string):Promise<string>;

export function RunSynapseSweep():Promise<string>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
