import { createServer } from 'node:http'
import { afterAll, afterEach, beforeAll, describe, expect, test } from 'vitest'
import { __resetDashboardStoreForTests, createAlert, getAlert, setWorkflowConfig } from '~/server/utils/alert-store'
import { runWorkflow } from '~/server/utils/workflow'

type MCPRequestBody = {
  namespace: string
  pod: string
  kind: string
  lines: number
}

type AgentRequestBody = {
  alert: { pod: string; namespace: string; kind: string }
  diagnostics: { describeOutput?: string; clusterEvents?: string[] }
  task: string
}

let server: ReturnType<typeof createServer> | null = null
let baseURL = ''
const mcpRequests: MCPRequestBody[] = []
const agentRequests: AgentRequestBody[] = []

beforeAll(async () => {
  server = createServer(async (req, res) => {
    const chunks: Buffer[] = []
    for await (const chunk of req) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk))
    }
    const raw = Buffer.concat(chunks).toString('utf8')
    const body = raw ? JSON.parse(raw) : {}

    if (req.url === '/mcp' && req.method === 'POST') {
      mcpRequests.push(body as MCPRequestBody)
      res.setHeader('content-type', 'application/json')
      res.end(JSON.stringify({
        lastLogLines: ['line-1', 'line-2'],
        describeOutput: 'describe pod output from mock mcp',
        clusterEvents: ['Back-off restarting failed container']
      }))
      return
    }

    if (req.url === '/agent' && req.method === 'POST') {
      agentRequests.push(body as AgentRequestBody)
      res.setHeader('content-type', 'application/json')
      res.end(JSON.stringify({
        generatedAt: '2026-03-08T10:00:00Z',
        summary: 'Generated by mocked agent',
        rootCause: 'Invalid imagePullSecret reference',
        recommendedActions: ['Fix imagePullSecret name', 'Redeploy workload'],
        confidence: 'high'
      }))
      return
    }

    res.statusCode = 404
    res.end('not found')
  })

  await new Promise<void>((resolve) => {
    server!.listen(0, 'localhost', () => {
      const address = server!.address()
      if (address && typeof address !== 'string') {
        baseURL = `http://localhost:${address.port}`
      }
      resolve()
    })
  })
})

afterEach(() => {
  __resetDashboardStoreForTests()
  mcpRequests.length = 0
  agentRequests.length = 0
})

afterAll(async () => {
  if (!server) return
  await new Promise<void>((resolve, reject) => {
    server!.close((err) => {
      if (err) reject(err)
      else resolve()
    })
  })
})

describe('alerts workflow integration', () => {
  test('runs full fallback workflow and generates local RCA when MCP/agent endpoints are not configured', async () => {
    const alert = createAlert({
      kind: 'CrashLoopBackOff',
      cluster: 'dev-cluster',
      namespace: 'payments',
      pod: 'checkout-api-abc',
      source: 'manual'
    })

    await runWorkflow(alert.id)

    const updated = getAlert(alert.id)
    expect(updated).toBeDefined()
    expect(updated!.status).toBe('report_ready')
    expect(updated!.thinkingSteps.map((s) => s.title)).toEqual([
      'Observer → API',
      'Thinker (MCP)',
      'Actor (Agent)'
    ])
    expect(updated!.diagnostics?.clusterEvents?.[0]).toContain('No external MCP endpoint configured')
    expect(updated!.report?.rootCause).toContain('startup probe')
    expect(mcpRequests.length).toBe(0)
    expect(agentRequests.length).toBe(0)
  })

  test('calls MCP and Agent endpoints, then stores returned diagnostics and RCA report', async () => {
    setWorkflowConfig({
      mcpEndpoint: `${baseURL}/mcp`,
      mcpApiKeyHeader: 'Authorization',
      mcpApiKey: 'mcp-token-123',
      agentEndpoint: `${baseURL}/agent`,
      agentApiKeyHeader: 'Authorization',
      agentApiKey: 'agent-token-123'
    })

    const alert = createAlert({
      kind: 'ImagePullBackOff',
      cluster: 'prod-eu',
      namespace: 'checkout',
      pod: 'checkout-api-xyz',
      source: 'kube-watcher',
      ruleName: 'Image-Pull-Failure'
    })

    await runWorkflow(alert.id)

    const updated = getAlert(alert.id)
    expect(updated).toBeDefined()
    expect(updated!.status).toBe('report_ready')
    expect(updated!.diagnostics?.describeOutput).toBe('describe pod output from mock mcp')
    expect(updated!.report?.rootCause).toBe('Invalid imagePullSecret reference')
    expect(updated!.report?.recommendedActions).toEqual(['Fix imagePullSecret name', 'Redeploy workload'])

    expect(mcpRequests).toHaveLength(1)
    expect(mcpRequests[0]).toEqual({
      namespace: 'checkout',
      pod: 'checkout-api-xyz',
      kind: 'ImagePullBackOff',
      lines: 50
    })

    expect(agentRequests).toHaveLength(1)
    expect(agentRequests[0].alert.pod).toBe('checkout-api-xyz')
    expect(agentRequests[0].diagnostics.describeOutput).toBe('describe pod output from mock mcp')
    expect(agentRequests[0].task).toContain('RCA')
  })
})
